<a href="https://colab.research.google.com/github/Raksh1707/taskdeeplearning/blob/main/task5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np


In [2]:
x = torch.randn(4, 5)
x.requires_grad = False

gamma = torch.ones(5)
beta = torch.zeros(5)

In [3]:

# Batch Normalization
def batch_norm(x):

    mean = x.mean(dim=0)
    var = x.var(dim=0, unbiased=False)

    x_hat = (x - mean) / torch.sqrt(var + 1e-5)

    out = gamma * x_hat + beta

    return out, mean, var, x_hat

In [4]:
def layer_norm(x):

    mean = x.mean(dim=1, keepdim=True)
    var = x.var(dim=1, keepdim=True, unbiased=False)

    x_hat = (x - mean) / torch.sqrt(var + 1e-5)

    out = gamma * x_hat + beta

    return out, x_hat

In [5]:
 # Manual Backward
# -----------------------
def backward(dout, x_hat):

    dgamma = torch.sum(dout * x_hat, dim=0)
    dbeta = torch.sum(dout, dim=0)

    return dgamma, dbeta

# BatchNorm
bn_out, running_mean, running_var, bn_hat = batch_norm(x)

# LayerNorm
ln_out, ln_hat = layer_norm(x)

# Dummy Gradient
dout = torch.ones_like(x)

# Backward
dgamma_bn, dbeta_bn = backward(dout, bn_hat)
dgamma_ln, dbeta_ln = backward(dout, ln_hat)


In [6]:
print("BatchNorm Output")
print(bn_out)

print("\nLayerNorm Output")
print(ln_out)

print("\nRunning Mean")
print(running_mean)

print("\nRunning Variance")
print(running_var)

print("\nBatchNorm dGamma:", dgamma_bn)
print("BatchNorm dBeta :", dbeta_bn)

print("\nLayerNorm dGamma:", dgamma_ln)
print("LayerNorm dBeta :", dbeta_ln)

BatchNorm Output
tensor([[-1.2080, -0.6072,  0.9556,  0.4670,  1.2708],
        [-0.7513,  0.9913, -0.9518,  0.0812,  0.3063],
        [ 1.1479, -1.3266,  1.0423,  1.0722, -0.0648],
        [ 0.8114,  0.9425, -1.0461, -1.6204, -1.5123]])

LayerNorm Output
tensor([[-1.2097, -0.9537,  1.0429, -0.1149,  1.2354],
        [-0.3220,  0.2496, -1.6755,  0.3743,  1.3735],
        [ 0.1711, -1.7205,  1.3954,  0.2373, -0.0833],
        [ 1.4515,  0.7449, -1.3713, -0.6549, -0.1702]])

Running Mean
tensor([-0.3820, -0.7442, -0.3963, -0.3640,  0.2806])

Running Variance
tensor([0.5061, 0.1139, 3.2663, 0.6367, 0.9989])

BatchNorm dGamma: tensor([1.1921e-07, 5.9605e-08, 1.1921e-07, 0.0000e+00, 1.1921e-07])
BatchNorm dBeta : tensor([4., 4., 4., 4., 4.])

LayerNorm dGamma: tensor([ 0.0909, -1.6797, -0.6084, -0.1582,  2.3554])
LayerNorm dBeta : tensor([4., 4., 4., 4., 4.])
